name: 'wetter_strom'
version: '1.0.0'
config-version: 2

profile: 'wetter_strom'

model-paths: ["models"]
macro-paths: ["macros"]

models:
  wetter_strom:
    staging:
      +materialized: view          # Staging = Views (kein Speicherverbrauch)
      +schema: staging
    analytics:
      +materialized: table         # Analytics = echte Tabellen (schnelle Queries)
      +schema: analytics

